services:
  subphim-server:
    build: .
    container_name: subphim_app
    restart: always
    ports:
      - "80:8080"  # Map port 80 của VM vào port 8080 của App
    volumes:
      - ./app_data:/data  # Lưu database và keys ra thư mục app_data bên ngoài container
    environment:
      - TZ=Asia/Ho_Chi_Minh # Cài đặt múi giờ Việt Nam
      # Thêm các cấu hình khác nếu cần thiết (ví dụ Email)
      # - SmtpSettings__Server=smtp.gmail.com
